defmodule Hateball.Cards.Constants do

  @questions [
    "______ + ______ = ______.",
    "______ is a slippery slope that leads to ______.",
    "______: kid-tested, mother-approved.",
    "______. betcha can't have just one!",
    "______. high five, bro.",
    "______. it's a trap!",
    "______. that was so metal.",
    "50% of all marriages end in ______.",
    "a recent laboratory study shows that undergraduates have 50% less sex after being exposed to ______.",
    "a romantic, candlelit dinner would be incomplete without ______.",
    "after eight years in the white house, how is obama finally letting loose?",
    "after four platinum albums and three grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ______.",
    "alternative medicine is now embracing the curative powers of ______.",
    "and the academy award for ______ goes to ______.",
    "arby's: we have ______.",
    "as the mom of five rambunctious boys, i'm no stranger to ______.",
    "bravo's new reality show features eight washed-up celebrities living with ______.",
    "brought to you by bud light®, the official beer of ______.",
    "but before i kill you, mr. bond, i must show you ______.",
    "check me out, yo! i call this dance move \"______.\"",
    "click here for ______!!!",
    "coming to broadway this season, ______: the musical.",
    "daddy, why is mommy crying?",
    "dear abby, i'm having some trouble with ______ and would like your advice.",
    "dude, do not go in that bathroom. there's ______ in there.",
    "during sex, i like to think about ______.",
    "for my next trick, i will pull ______ out of ______.",
    "fun tip! when your man asks you to go down on him, try surprising him with ______ instead.",
    "here is the church\nhere is the steeple\nopen the doors\nand there is ______.",
    "hey guys, welcome to chili's! would you like to start the night off right with ______?",
    "hey reddit! i'm ______. ask me anything.",
    "how did i lose my virginity?",
    "i drink to forget ______.",
    "i get by with a little help from ______.",
    "i got 99 problems but ______ ain't one.",
    "i never truly understood ______ until i encountered ______.",
    "i'm going on a cleanse this week. nothing but kale juice and ______.",
    "i'm lebron james, and when i'm not slamming dunks, i love ______.",
    "i'm no doctor, but i'm pretty sure what you're suffering from is called \"______.\"",
    "i'm sorry, professor, but i couldn't complete my homework because of ______.",
    "if you can't be with the one you love, love ______.",
    "if you like ______, you might be a redneck.",
    "in m. night shyamalan's new movie, bruce willis discovers that ______ had really been ______ all along.",
    "in the new disney channel original movie, hannah montana struggles with ______ for the first time.",
    "instead of coal, santa now gives the bad children ______.",
    "introducing the amazing superhero/sidekick duo! it's ______ and ______!",
    "introducing x-treme baseball! it's like baseball, but with ______!",
    "it’s a pity that kids these days are all getting involved with ______.",
    "just once, i'd like to hear you say \"thanks, mom. thanks for ______.\"",
    "just saw this upsetting video! please retweet!! #stop______",
    "kids, i don't need drugs to get high. i'm high on ______.",
    "life for american indians was forever changed when the white man introduced them to ______.",
    "lifetime® presents \"______: the story of ______.\"",
    "make a haiku.",
    "maybe she's born with it. maybe it's ______.",
    "men's wearhouse: you're gonna like ______. i guarantee it.",
    "military historians remember alexander the great for his brilliant use of ______ against the persians.",
    "mr. and mrs. diaz, we called you in because we're concerned about cynthia. are you aware that your daughter is ______?",
    "my fellow americans: before this decade is out, we will have ______ on the moon!",
    "next from j.k. rowling: harry potter and the chamber of ______.",
    "next on espn2: the world series of ______.",
    "old macdonald had ______. e-i-e-i-o.",
    "step 1: ______.\nstep 2: ______.\nstep 3: profit.",
    "that's right, i killed ______. how, you ask? ______.",
    "the class field trip was completely ruined by ______.",
    "the new chevy tahoe. with the power and space to take ______ everywhere you go.",
    "they said we were crazy. they said we couldn't put ______ inside of ______. they were wrong.",
    "this is the way the world ends\nthis is the way the world ends\nnot with a bang but with ______.",
    "this season at steppenwolf, samuel beckett's classic existential play: waitng for ______.",
    "today on maury: \"help! my son is ______!\"",
    "tsa guidelines now prohibit ______ on airplanes.",
    "uh, hey guys, i know this was my idea, but i'm having serious doubts about ______.",
    "war! what is it good for?",
    "well if you'll excuse me, gentlemen, i have a date with ______.",
    "what are my parents hiding from me?",
    "what ended my last relationship?",
    "what gives me uncontrollable gas?",
    "what is batman's guilty pleasure?",
    "what is george w. bush thinking about right now?",
    "what made my first kiss so awkward?",
    "what makes life worth living?",
    "what never fails to liven up the party?",
    "what will always get you laid?",
    "what would grandma find disturbing, yet oddly charming?",
    "what's a girl's best friend?",
    "what's my secret power?",
    "what's teach for america using to inspire inner city students to succeed?",
    "what's that smell?",
    "what's that sound?",
    "what's there a ton of in heaven?",
    "when i am a billionare, i shall erect a 50-foot statue to commemorate ______.",
    "when i am president, i will create the department of ______.",
    "when i was tripping on acid, ______ turned into ______.",
    "when pharaoh remained unmoved, moses called down a plague of ______.",
    "while the united states raced the soviet union to the moon, the mexican government funneled millions of pesos into research on ______.",
    "white people like ______."
  ]

  @answers [
    "why am i sticky?",
    "why can't i sleep at night?",
    "why do i hurt all over?",
    "10,000 Syrian refugees.",
    "50 mg of Zoloft daily.",
    "50,000 volts straight to the nipples.",
    "72 virgins.",
    "8 oz. of sweet Mexican black-tar heroin.",
    "A bag of magic beans.",
    "A balanced breakfast.",
    "A ball of earwax, semen, and toenail clippings.",
    "A bird that shits human turds.",
    "A bitch slap.",
    "A bleached asshole.",
    "A Bop It™.",
    "A bowl of mayonnaise and human teeth.",
    "A brain tumor.",
    "A crucifixion.",
    "A disappointing birthday party.",
    "A falcon with a cap on its head.",
    "A fart so powerful that it wakes the giants from their thousand-year slumber.",
    "A fetus.",
    "A Fleshlight.",
    "A fuck-ton of almonds.",
    "A good sniff.",
    "A good, strong gorilla.",
    "A gossamer stream of jizz that catches the light as it arcs through the morning air.",
    "A homoerotic volleyball montage.",
    "A horde of Vikings.",
    "A lifetime of sadness.",
    "A little boy who won't shut the fuck up about dinosaurs.",
    "A live studio audience.",
    "A man on the brink of orgasm.",
    "A mating display.",
    "A Mexican.",
    "A micropenis.",
    "A micropig wearing a tiny raincoat and booties.",
    "A middle-aged man on roller skates.",
    "A mopey zoo lion.",
    "A much younger woman.",
    "A pangender octopus who roams the cosmos in search of love.",
    "A pyramid of severed heads.",
    "A really cool hat.",
    "A sad handjob.",
    "A salad for men that's made of metal.",
    "A salty surprise.",
    "A sassy black woman.",
    "A saxophone solo.",
    "A sea of troubles.",
    "A snapping turtle biting the tip of your penis.",
    "A stray pube.",
    "A Super Soaker™ full of cat pee.",
    "A three-way with my wife and Shaquille O'Neal.",
    "A time travel paradox.",
    "A tiny horse.",
    "A tiny, gay guitar called a ukulele.",
    "A whole thing of butter.",
    "A windmill full of corpses.",
    "Aaron Burr.",
    "Academy Award winner Meryl Streep.",
    "Accepting the way things are.",
    "Active listening.",
    "Adderall™.",
    "African children.",
    "Agriculture.",
    "AIDS.",
    "Alcoholism.",
    "All the dudes I've fucked.",
    "All-you-can-eat shrimp for $8.99.",
    "An AR-15 assault rifle.",
    "An endless stream of diarrhea.",
    "An erection that lasts longer than four hours.",
    "An M. Night Shyamalan plot twist.",
    "An octopus giving seven handjobs and smoking a cigarette.",
    "An Oedipus complex.",
    "An old guy who's almost dead.",
    "An older woman who knows her way around the penis.",
    "An oversized lollipop.",
    "An unwanted pregnancy.",
    "Anal beads.",
    "Announcing that I am about to cum.",
    "Arnold Schwarzenegger.",
    "Assless chaps.",
    "Auschwitz.",
    "Authentic Mexican cuisine.",
    "Autocannibalism.",
    "AXE Body Spray.",
    "Balls.",
    "Bananas.",
    "Barack Obama.",
    "BATMAN!",
    "Battlefield amputations.",
    "Becoming a blueberry.",
    "Bees?",
    "Being a dick to children.",
    "Being a motherfucking sorcerer.",
    "Being a woman.",
    "Being able to talk to elephants.",
    "Being fat and stupid.",
    "Being marginalized.",
    "Being on fire.",
    "Being rich.",
    "Bill Nye the Science Guy.",
    "Bingeing and purging.",
    "Bisexuality.",
    "Bitches.",
    "Black people.",
    "Blowing my boyfriend so hard he shits.",
    "Boogers.",
    "Braiding three penises into a Twizzler.",
    "Breaking out into song and dance.",
    "Brown people.",
    "Bubble butt bottom boys.",
    "Casually suggesting a threesome.",
    "Catapults.",
    "Centaurs.",
    "Chainsaws for hands.",
    "Chemical weapons.",
    "Child abuse.",
    "Child beauty pageants.",
    "Chunks of dead hitchhiker.",
    "Coat hanger abortions.",
    "Committing suicide.",
    "Completely unwarranted confidence.",
    "Concealing a boner.",
    "Consensual sex.",
    "Count Chocula.",
    "Covering myself with Parmesan cheese and chili flakes because I am pizza.",
    "Crippling debt.",
    "Crumbs all over the god damn carpet.",
    "Cuddling.",
    "Daddy issues.",
    "Daniel Radcliffe's delicious asshole.",
    "Danny DeVito.",
    "Dark and mysterious forces beyond our control.",
    "Darth Vader.",
    "David Bowie flying in on a tiger made of lightning.",
    "Dead babies.",
    "Dead birds everywhere.",
    "Dead parents.",
    "Dick fingers.",
    "Dick pics.",
    "Diversity.",
    "Doin' it in the butt.",
    "Doing crimes.",
    "Doing the right thing.",
    "Donald J. Trump.",
    "Drinking alone.",
    "Drinking out of the toilet and eating garbage.",
    "Drowning the kids in the bathtub.",
    "Dry heaving.",
    "Dwayne \"The Rock\" Johnson.",
    "Dying.",
    "Eating a hard boiled egg out of my husband's asshole.",
    "Eating the last known bison.",
    "Elderly Japanese men.",
    "Emerging from the sea and rampaging through Tokyo.",
    "Emma Watson.",
    "Emotions.",
    "Erectile dysfunction.",
    "Establishing dominance.",
    "Estrogen.",
    "Ethnic cleansing.",
    "Exactly what you'd expect.",
    "Executing a hostage every hour.",
    "Expecting a burp and vomiting on the floor.",
    "Explaining how vaginas work.",
    "Explosions.",
    "Extremely tight pants.",
    "Facebook.",
    "Fading away into nothingness.",
    "Fake tits.",
    "Famine.",
    "Fancy Feast®.",
    "Farting and walking away.",
    "Fear itself.",
    "Fellowship in Christ.",
    "Fiery poops.",
    "Filling my briefcase with business stuff.",
    "Finger painting.",
    "Firing a rifle into the air while balls deep in a squealing hog.",
    "Flesh-eating bacteria.",
    "Flightless birds.",
    "Flying sex snakes.",
    "Forced sterilization.",
    "Foreskin.",
    "Former President George W. Bush.",
    "Fox News.",
    "Fragile masculinity.",
    "Free samples.",
    "Friction.",
    "Fucking my sister.",
    "Fucking the weatherman on live television.",
    "Full frontal nudity.",
    "Funky fresh rhymes.",
    "Gandhi.",
    "Gay conversion therapy.",
    "Geese.",
    "Genuine human connection.",
    "German Chancellor Angela Merkel.",
    "German dungeon porn.",
    "Getting crushed by a vending machine.",
    "Getting cummed on.",
    "Getting drugs off the street and into my body.",
    "Getting fingered.",
    "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.",
    "Getting naked and watching Nickelodeon.",
    "Getting really high.",
    "Getting so angry that you pop a boner.",
    "Ghosts.",
    "Girls.",
    "Giving 110%.",
    "Giving birth to the Antichrist.",
    "Gloryholes.",
    "Goblins.",
    "God.",
    "GoGurt®.",
    "Going an entire day without masturbating.",
    "Grandma.",
    "Half-assed foreplay.",
    "Harry Potter erotica.",
    "Having anuses for eyes.",
    "Having big dreams but no realistic way to achieve them.",
    "Having sex for the first time.",
    "Heartwarming orphans.",
    "Her Majesty, Queen Elizabeth II.",
    "Heteronormativity.",
    "Hillary Clinton's emails.",
    "Hobos.",
    "Holding down a child and farting all over him.",
    "Hope.",
    "Horse meat.",
    "Hospice care.",
    "Hot cheese.",
    "Hot people.",
    "How amazing it is to be on mushrooms.",
    "How bad my daughter fucked up her dance recital.",
    "How far I can get my own penis up my butt.",
    "However much weed $20 can buy.",
    "Huffing spray paint.",
    "Huge biceps.",
    "Illegal immigrants.",
    "Inappropriate yodeling.",
    "Incest.",
    "Inserting a Mason jar into my anus.",
    "Invading Poland.",
    "Italians.",
    "Itchy pussy.",
    "J.D. Power and his associates.",
    "Jennifer Lawrence.",
    "Jerking off into a pool of children's tears.",
    "Jews, gypsies, and homosexuals.",
    "Jobs.",
    "Judge Judy.",
    "Judging everyone.",
    "Justin Bieber.",
    "Kamikaze pilots.",
    "Kanye West.",
    "Kissing grandma on the forehead and turning off her life support.",
    "Kourtney, Kim, Khloe, Kendall, and Kylie.",
    "Lactation.",
    "Lance Armstrong's missing testicle.",
    "Land mines.",
    "Laying an egg.",
    "Lena Dunham.",
    "Leprosy.",
    "Liberals.",
    "Licking things to claim them as your own.",
    "Listening to her problems without trying to solve them.",
    "Lockjaw.",
    "Looking in the mirror, applying lipstick, and whispering \"tonight, you will have sex with Tom Cruise.\"",
    "Lumberjack fantasies.",
    "Lunchables™.",
    "Magnets.",
    "Making a pouty face.",
    "Man meat.",
    "Mansplaining.",
    "Many bats.",
    "Masturbating.",
    "Me time.",
    "MechaHitler.",
    "Memes.",
    "Men discussing their feelings in an emotionally healthy way.",
    "Men.",
    "Menstrual rage.",
    "Meth.",
    "Mike Pence.",
    "More elephant cock than I bargained for.",
    "Morgan Freeman's voice.",
    "Mouth herpes.",
    "Muhammad (Peace Be Upon Him).",
    "Multiple stab wounds.",
    "Murder.",
    "Mutually assured destruction.",
    "My abusive boyfriend who really isn't so bad once you get to know him.",
    "My balls on your face.",
    "My black ass.",
    "My bright pink fuckhole.",
    "My cheating son-of-a-bitch husband.",
    "My collection of Japanese sex toys.",
    "My ex-wife.",
    "My fat daughter.",
    "My genitals.",
    "My good bra.",
    "My inner demons.",
    "My neck, my back, my pussy, and my crack.",
    "My relationship status.",
    "My sex life.",
    "My soul.",
    "My Uber driver, Pavel.",
    "My ugly face and bad personality.",
    "My vagina.",
    "Natural male enhancement.",
    "Natural selection.",
    "Nazis.",
    "NBA superstar LeBron James.",
    "Necrophilia.",
    "Nickelback.",
    "Nicolas Cage.",
    "Nipple blades.",
    "Not giving a shit about the Third World.",
    "Not reciprocating oral sex.",
    "Not vaccinating my children because I am stupid.",
    "Not wearing pants.",
    "Object permanence.",
    "Old-people smell.",
    "One titty hanging out.",
    "One trillion dollars.",
    "Only dating Asian women.",
    "Oompa-Loompas.",
    "Opposable thumbs.",
    "Oprah.",
    "Pac-Man uncontrollably guzzling cum.",
    "Passive-aggressive Post-it notes.",
    "Pedophiles.",
    "Peeing a little bit.",
    "Penis breath.",
    "Penis envy.",
    "Permanent Orgasm-Face Disorder.",
    "Pictures of boobs.",
    "Pixelated bukkake.",
    "Police brutality.",
    "Pooping back and forth. Forever.",
    "Pooping in a laptop and closing it.",
    "Poopy diapers.",
    "Poor life choices.",
    "Poor people.",
    "Poorly-timed Holocaust jokes.",
    "Poverty.",
    "Powerful thighs.",
    "Prescription pain killers.",
    "Preteens.",
    "Pretending to care.",
    "PTSD.",
    "Puberty.",
    "Pulling out.",
    "Punching a congressman in the face.",
    "Puppies!",
    "Queefing.",
    "Racially-biased SAT questions.",
    "Racism.",
    "Radical Islamic terrorism.",
    "Rap music.",
    "Raptor attacks.",
    "Repression.",
    "Republicans.",
    "RoboCop.",
    "Ronald Reagan.",
    "Running out of semen.",
    "Ruth Bader Ginsburg brutally gaveling your penis.",
    "Saying \"I love you.\"",
    "Science.",
    "Scientology.",
    "Seeing Grandma naked.",
    "Seeing my father cry.",
    "Seeing what happens when you lock people in a room with hungry seagulls.",
    "Seething with quiet resentment.",
    "Self-loathing.",
    "Selling crack to children.",
    "Seppuku.",
    "Serfdom.",
    "Seven dead and three in critical condition.",
    "Sex with animals.",
    "Sex with Patrick Stewart.",
    "Sexual peeing.",
    "Sexual tension.",
    "Shaking a baby until it stops crying.",
    "Shapeshifters.",
    "Shiny objects.",
    "Shutting up so I can watch the game.",
    "Sideboob.",
    "Silence.",
    "Sitting on my face and telling me I'm garbage.",
    "Slaughtering innocent civilians.",
    "Smallpox blankets.",
    "Smegma.",
    "Soft, kissy missionary sex.",
    "Solving problems with violence.",
    "Some god damn peace and quiet.",
    "Some guy.",
    "Some of the best rappers in the game.",
    "Some punk kid who stole my turkey sandwich.",
    "Soup that is too hot.",
    "Spaghetti? Again?",
    "Spectacular abs.",
    "Sperm whales.",
    "Spontaneous human combustion.",
    "Stalin.",
    "Stephen Hawking talking dirty.",
    "Steve Bannon.",
    "Still being a virgin.",
    "Strong female characters.",
    "Sunshine and rainbows.",
    "Sweet, sweet vengeance.",
    "Switching to Geico®.",
    "Swooping.",
    "Synergistic management solutions.",
    "Tap dancing like there's no tomorrow.",
    "Teaching a robot to love.",
    "Tearing that ass up like wrapping paper on Christmas morning.",
    "Teenage pregnancy.",
    "Telling a shitty story that goes nowhere.",
    "Tentacle porn.",
    "The American Dream.",
    "The Amish.",
    "The arrival of the pizza.",
    "The Bachelorette season finale.",
    "The Big Bang.",
    "The Blood of Christ.",
    "The bombing of Nagasaki.",
    "The Boy Scouts of America.",
    "The clitoris.",
    "The cool, refreshing taste of Pepsi®.",
    "The Devil Himself.",
    "The entire Mormon Tabernacle Choir.",
    "The female orgasm.",
    "The Force.",
    "The gays.",
    "The glass ceiling.",
    "The Great Depression.",
    "The Hamburglar.",
    "The heart of a child.",
    "The Holy Bible.",
    "The homosexual agenda.",
    "The Hustle.",
    "The inevitable heat death of the universe.",
    "The Jews.",
    "The KKK.",
    "The Kool-Aid Man.",
    "The magic of live theatre.",
    "The milkman.",
    "The miracle of childbirth.",
    "The only gay person in a hundred miles.",
    "The past.",
    "The Patriarchy.",
    "The penny whistle solo from \"My Heart Will Go On.\"",
    "The placenta.",
    "The Pope.",
    "The Rapture.",
    "The Red Hot Chili Peppers.",
    "The rhythms of Africa.",
    "The Russians.",
    "The screams...the terrible screams.",
    "The South.",
    "The Three-Fifths compromise.",
    "The Trail of Tears.",
    "The true meaning of Christmas.",
    "The Underground Railroad.",
    "The unstoppable tide of Islam.",
    "The violation of our most basic human rights.",
    "The wifi password.",
    "The wonders of the Orient.",
    "These hoes.",
    "This month's mass shooting.",
    "Three dicks at the same time.",
    "Throwing a virgin into a volcano.",
    "Throwing grapes at a man until he loses touch with reality.",
    "Touching a pug right on his penis.",
    "Unfathomable stupidity.",
    "Used panties.",
    "Vehicular manslaughter.",
    "Viagra®.",
    "Vigorous jazz hands.",
    "Vladimir Putin.",
    "Vomiting seafood and bleeding anally.",
    "Waiting till marriage.",
    "Waking up half-naked in a Denny's parking lot.",
    "Wet dreams.",
    "Whipping it out.",
    "White people.",
    "White privilege.",
    "William Shatner.",
    "Wizard music.",
    "Women in yogurt commercials.",
    "Women of color.",
    "Women's suffrage.",
    "Wondering if it's possible to get some of that salsa to go.",
    "World peace.",
    "Worshipping that pussy.",
    "Yeast.",
    "Your weird brother."
  ]

  def get_questions do
    @questions
  end

  def get_answers do
    @answers
  end


end
